# Generated by Django 5.2.5 on 2025-09-29 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_leaverequest_status'),
        ('substitution', '0002_substitution_class_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='substitution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_request', to='substitution.substitution'),
        ),
    ]
