# Generated by Django 5.2.5 on 2025-09-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitution',
            name='class_label',
            field=models.CharField(blank=True, help_text='Class/Subject/Period name (e.g., CS101, Database Lecture)', max_length=100, null=True),
        ),
    ]
